import { Property, Review } from '../types';

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    name: 'Prestige Lakeside Habitat',
    locality: 'Varthur, Whitefield',
    city: 'Bangalore',
    type: 'Apartment',
    avgRating: 4.4,
    ratingsCount: 18,
    subRatings: {
      maintenance: 4.5,
      communication: 4.2,
      depositReturn: 4.1,
      safety: 4.8,
    },
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-01-15T10:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prop-2',
    name: 'Hiranandani Gardens Estate',
    locality: 'Powai',
    city: 'Mumbai',
    type: 'Apartment',
    avgRating: 4.7,
    ratingsCount: 24,
    subRatings: {
      maintenance: 4.8,
      communication: 4.6,
      depositReturn: 4.5,
      safety: 4.9,
    },
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-02-10T11:30:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prop-3',
    name: 'DLF Phase 5 Luxury Residency',
    locality: 'Golf Course Road',
    city: 'Gurgaon',
    type: 'Apartment',
    avgRating: 3.8,
    ratingsCount: 12,
    subRatings: {
      maintenance: 3.9,
      communication: 3.5,
      depositReturn: 3.2,
      safety: 4.6,
    },
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-03-05T09:15:00.000Z',
  },
  {
    id: 'prop-4',
    name: 'Amanora Park Town Heights',
    locality: 'Hadapsar',
    city: 'Pune',
    type: 'Apartment',
    avgRating: 4.2,
    ratingsCount: 9,
    subRatings: {
      maintenance: 4.1,
      communication: 4.3,
      depositReturn: 4.0,
      safety: 4.5,
    },
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-03-20T14:20:00.000Z',
  },
  {
    id: 'prop-5',
    name: 'Stanza Living - Silicon Valley House',
    locality: 'Koramangala 4th Block',
    city: 'Bangalore',
    type: 'PG',
    avgRating: 4.1,
    ratingsCount: 31,
    subRatings: {
      maintenance: 4.0,
      communication: 4.2,
      depositReturn: 3.9,
      safety: 4.4,
    },
    imageUrl: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-04-01T08:00:00.000Z',
  },
  {
    id: 'prop-6',
    name: 'My Home Bhooja Towers',
    locality: 'HITEC City',
    city: 'Hyderabad',
    type: 'Apartment',
    avgRating: 4.8,
    ratingsCount: 15,
    subRatings: {
      maintenance: 4.9,
      communication: 4.7,
      depositReturn: 4.8,
      safety: 4.9,
    },
    imageUrl: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-04-18T16:45:00.000Z',
  },
  {
    id: 'prop-7',
    name: 'Brigade Gateway Apartments',
    locality: 'Rajajinagar',
    city: 'Bangalore',
    type: 'Apartment',
    avgRating: 4.5,
    ratingsCount: 21,
    subRatings: {
      maintenance: 4.6,
      communication: 4.4,
      depositReturn: 4.3,
      safety: 4.7,
    },
    imageUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-05-02T12:10:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prop-8',
    name: 'SNN Raj Greenbay Studio Suites',
    locality: 'Electronic City Phase 1',
    city: 'Bangalore',
    type: 'Studio Apartment',
    avgRating: 4.6,
    ratingsCount: 14,
    subRatings: {
      maintenance: 4.7,
      communication: 4.5,
      depositReturn: 4.4,
      safety: 4.8,
    },
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-05-10T14:00:00.000Z',
  },
  {
    id: 'prop-9',
    name: 'Cyber City Commercial Tech Park',
    locality: 'DLF Phase 2',
    city: 'Gurgaon',
    type: 'Commercial',
    avgRating: 4.3,
    ratingsCount: 19,
    subRatings: {
      maintenance: 4.4,
      communication: 4.2,
      depositReturn: 4.1,
      safety: 4.6,
    },
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-05-18T10:00:00.000Z',
    isFeatured: true,
  },
  {
    id: 'prop-10',
    name: 'Jubilee Hills Independent Villa',
    locality: 'Jubilee Hills',
    city: 'Hyderabad',
    type: 'House',
    avgRating: 4.8,
    ratingsCount: 8,
    subRatings: {
      maintenance: 4.8,
      communication: 4.7,
      depositReturn: 4.8,
      safety: 4.9,
    },
    imageUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-05-25T11:15:00.000Z',
  },
  {
    id: 'prop-11',
    name: 'Bhiwandi Logistics Hub & Warehouse',
    locality: 'Bhiwandi Industrial Area',
    city: 'Mumbai',
    type: 'Warehouse',
    avgRating: 4.2,
    ratingsCount: 11,
    subRatings: {
      maintenance: 4.1,
      communication: 4.3,
      depositReturn: 4.0,
      safety: 4.4,
    },
    imageUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    createdAt: '2024-06-01T08:30:00.000Z',
  }
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    propertyId: 'prop-1',
    propertyTitle: 'Prestige Lakeside Habitat',
    authorUid: 'user-sample-1',
    authorName: 'Rohan_Bangalore',
    isVerifiedTenant: true,
    isFirsthand: true,
    rating: 5,
    subRatings: {
      maintenance: 5,
      communication: 5,
      depositReturn: 4,
      safety: 5,
    },
    comment:
      'Lived in Tower 14 for 2 years (2022-2024). The maintenance team responds within 2 hours on the resident app. Security is strict at all gates. Landlord deducted ₹3,000 for paint touchup out of ₹1.5L deposit which was reasonable and fully itemized with bills.',
    createdAt: '2024-05-15T14:30:00.000Z',
    ownerResponse: {
      text: 'Thank you Rohan! Glad to know your stay was pleasant. We strive to maintain strict transparency on security deposit returns.',
      createdAt: '2024-05-16T10:00:00.000Z',
      ownerUid: 'owner-sample-1',
      ownerName: 'Prestige Management Office',
    }
  },
  {
    id: 'rev-2',
    propertyId: 'prop-1',
    propertyTitle: 'Prestige Lakeside Habitat',
    authorUid: 'user-sample-2',
    authorName: 'Ananya_S',
    isVerifiedTenant: true,
    isFirsthand: true,
    rating: 4,
    subRatings: {
      maintenance: 4,
      communication: 4,
      depositReturn: 4,
      safety: 5,
    },
    comment:
      'Great amenities and lush greenery. Power backup works uninterrupted during monsoon cuts. Water quality is treated RO standard.',
    createdAt: '2024-06-01T09:20:00.000Z',
  },
  {
    id: 'rev-3',
    propertyId: 'prop-3',
    propertyTitle: 'DLF Phase 5 Luxury Residency',
    authorUid: 'user-sample-3',
    authorName: 'Karan_Gurgaon',
    isVerifiedTenant: true,
    isFirsthand: true,
    rating: 3,
    subRatings: {
      maintenance: 3,
      communication: 3,
      depositReturn: 2,
      safety: 4,
    },
    comment:
      'Flat condition is good but landlord delayed returning the ₹2 Lakh deposit by 45 days after lease end. Took multiple followups and reminders. Maintenance requests took 3-4 days.',
    createdAt: '2024-06-10T16:00:00.000Z',
  }
];
